In [45]:
import pandas as pd

In [46]:
#import csv files
batsmen = pd.read_csv('batsmanT20.csv')
bowlers = pd.read_csv('BowlerT20.csv')
bowlers

,Player Name,Country,Time Period,Matches,Played,Overs,Maiden Overs,Runs,Wickets,Best Figure,Bowling Average,Economy Rate,Strike Rate,Four Wickets,Five Wickets
0,B Kumar,India,2016-2022,6,6,23.0,3,123,13,5/4,9.46,5.34,10.6,1,1
1,Amjad Javed,UAE,2016-2016,7,7,23.0,0,169,12,3/25,14.08,7.34,11.5,0,0
2,Al-Amin Hossain,Bangladesh,2016-2016,5,5,16.5,0,134,11,3/25,12.18,7.96,9.1,0,0
3,Mohammad Naveed,UAE,2016-2016,7,7,27.4,2,145,11,3/14,13.18,5.24,15.0,0,0
4,Rashid Khan,Afghanistan,2016-2022,8,8,31.0,0,202,11,3/22,18.36,6.51,16.9,0,0
5,HH Pandya,India,2016-2022,8,8,29.3,1,207,11,3/8,18.81,7.01,16.0,0,0
6,PWH de Silva,Sri Lanka,2022-2022,6,6,23.0,0,170,9,3/21,18.88,7.39,15.3,0,0
7,Shadab Khan,Pakistan,2022-2022,5,5,18.4,0,113,8,4/8,14.12,6.05,14.0,1,0
8,Haris Rauf,Pakistan,2022-2022,6,6,20.0,0,153,8,3/29,19.12,7.65,15.0,0,0
9,Mohammad Nawaz,Pakistan,2016-2022,8,8,24.4,0,174,8,3/5,21.75,7.05,18.5,0,0
10,Mohammad Amir,Pakistan,2016-2016,4,4,16.0,1,81,7,3/18,11.57,5.06,13.7,0,0
11,KMDN Kulasekara,Sri Lanka,2016-2016,4,4,15.0,1,95,7,3/10,13.57,6.33,12.8,0,0
12,Mujeeb Ur Rahman,Afghanistan,2022-2022,5,5,20.0,0,111,7,3/16,15.85,5.55,17.1,0,0
13,Naseem Shah,Pakistan,2022-2022,5,5,18.0,0,138,7,2/7,19.71,7.66,15.4,0,0
14,C Karunaratne,Sri Lanka,2022-2022,6,6,16.0,0,145,7,2/27,20.71,9.06,13.7,0,0
15,Mohammad Nabi,Afghanistan,2016-2022,8,8,29.0,0,210,7,4/17,30.00,7.24,24.8,1,0
16,PM Liyanagamage,Sri Lanka,2022-2022,2,2,6.1,0,55,6,4/34,9.16,8.91,6.1,1,0
17,JJ Bumrah,India,2016-2016,5,5,18.0,2,94,6,2/27,15.66,5.22,18.0,0,0
18,A Nehra,India,2016-2016,4,4,14.0,0,99,6,3/23,16.50,7.07,14.0,0,0
19,R Ashwin,India,2016-2022,6,6,22.0,0,143,6,2/26,23.83,6.50,22.0,0,0
20,Rohan Mustafa,UAE,2016-2016,7,7,20.5,0,146,6,3/19,24.33,7.00,20.8,0,0
21,Fazalhaq Farooqi,Afghanistan,2022-2022,5,5,18.1,1,152,6,3/11,25.33,8.36,18.1,0,0
22,Shakib Al Hasan,Bangladesh,2016-2022,7,7,24.4,0,152,6,2/20,25.33,6.16,24.6,0,0
23,D Madushanka,Sri Lanka,2022-2022,6,6,20.0,0,155,6,3/24,25.83,7.75,20.0,0,0
24,M Theekshana,Sri Lanka,2022-2022,6,6,24.0,0,162,6,2/21,27.00,6.75,24.0,0,0
25,Mohammad Irfan,Pakistan,2016-2016,4,4,16.0,0,87,5,2/18,17.40,5.43,19.2,0,0
26,Fareed Ahmad,Afghanistan,2022-2022,2,2,8.0,0,88,5,3/31,17.60,11.00,9.6,0,0
27,Mashrafe Mortaza,Bangladesh,2016-2016,5,5,16.0,0,114,5,2/12,22.80,7.12,19.2,0,0
28,Taskin Ahmed,Bangladesh,2016-2022,7,7,23.0,1,138,5,2/24,27.60,6.00,27.6,0,0
29,Arshdeep Singh,India,2022-2022,5,5,17.3,0,151,5,2/33,30.20,8.62,21.0,0,0
30,SL Malinga,Sri Lanka,2016-2016,1,1,4.0,0,26,4,4/26,6.50,6.50,6.0,1,0
31,Mahmudullah,Bangladesh,2016-2022,7,3,6.0,0,28,4,2/5,7.00,4.66,9.0,0,0
32,Nadeem Ahmed,Hong Kong,2016-2016,3,3,12.0,1,77,4,3/27,19.25,6.41,18.0,0,0
33,Aamir Kaleem,Oman,2016-2016,3,3,10.0,0,84,4,4/36,21.00,8.40,15.0,1,0
34,Bilal Khan,Oman,2016-2016,3,3,11.0,0,91,4,3/33,22.75,8.27,16.5,0,0
35,RA Jadeja,India,2016-2022,6,6,18.0,0,106,4,2/11,26.50,5.88,27.0,0,0
36,YS Chahal,India,2022-2022,4,4,16.0,0,127,4,3/34,31.75,7.93,24.0,0,0
37,Mohammad Hasnain,Pakistan,2022-2022,4,4,15.0,0,134,4,2/21,33.50,8.93,22.5,0,0
38,Mustafizur Rahman,Bangladesh,2016-2022,5,5,19.0,0,134,4,2/13,33.50,7.05,28.5,0,0
39,Mohammad Shahzad,UAE,2016-2016,7,7,19.1,0,156,4,2/27,39.00,8.13,28.7,0,0
40,Aizaz Khan,Hong Kong,2016-2022,5,5,17.3,0,189,4,3/38,47.25,10.80,26.2,0,0

In [47]:
# Creating a dataframe for batsmen and bowlers with specified columns.
batdf = pd.DataFrame( batsmen, columns=['Player Name','Batting Average','Balls Faced', 'Fours', 'Sixes'])
balldf = pd.DataFrame( bowlers, columns=['Player Name','Economy Rate','Wickets','Bowling Average'])

In [48]:
batdf

            Player Name Batting Average  Balls Faced  Fours  Sixes
0              V Kohli            85.80          325     40     11
1      Mohammad Rizwan            56.20          239     21      6
2            RG Sharma            30.11          192     27     12
3          Babar Hayat            47.00          160     22     10
4       Ibrahim Zadran            65.33          188     14      4
5        PBB Rajapaksa            47.75          128     15      9
6        Sabbir Rahman            36.20          148     16      5
7       Muhammad Usman            29.33          149     21      5
8    Najibullah Zadran            35.20          112      6     13
9           P Nissanka            34.60          150     15      5
10         Mahmudullah            57.66          122     10      7
11          BKG Mendis            25.83           99     10      9
12  Rahmanullah Gurbaz            30.40           93      8     12
13       Shaiman Anwar            25.16          144     15      4
14        LD Chandimal            37.25          136     19      2
15            SA Yadav            34.75           85     10      8
16          TM Dilshan            44.00          109     18      1
17            KL Rahul            26.40          108      8      6
18          MD Shanaka            14.55          111      9      6
19    Mohammad Shahzad            21.50          107     10      4
20       Rohan Mustafa            17.42          107     13      6
21      Sarfaraz Ahmed            60.50           93     14      2
22        Shoaib Malik            60.50          108     13      4
23     Zeeshan Maqsood            38.33           97     11      4
24     Shakib Al Hasan            16.00          115     12      0
25          Umar Akmal            35.00           98      6      5
26      Iftikhar Ahmed            26.25          104      6      3
27        Fakhar Zaman            16.00           93      9      2
28       Soumya Sarkar            18.80           88     11      2
29   Hazratullah Zazai            23.25           91     14      1
30    Asghar Stanikzai            29.66           61     10      4
31        Yuvraj Singh            44.50           80     10      4
32     Muhammad Kaleem            12.71          104      9      3
33           HH Pandya            16.60           56      8      3
34         Karim Sadiq            27.33           58      9      1
35            S Dhawan            26.33           71     12      1
36      Mohammad Nawaz            15.80           55      8      4
37         Adnan Ilyas            26.00           46      4      5
38    Mosaddek Hossain                -           40      8      1
39     Noor Ali Zadran            36.00           61      9      0
40      Jatinder Singh            23.00           68      7      1
41          Babar Azam            11.33           63      7      0
42       C Karunaratne            33.00           64      5      2
43        PWH de Silva            22.00           44     10      1
44             KD Shah            13.00           60      8      2
45      MD Gunathilaka            10.50           58      7      2
46       Anshuman Rath            20.66           70      7      0
47         Amjad Javed            12.20           66      4      3
48       Khushdil Shah            14.50           48      1      5

In [49]:
balldf

           Player Name  Economy Rate  Wickets  Bowling Average
0             B Kumar           5.34       13             9.46
1         Amjad Javed           7.34       12            14.08
2     Al-Amin Hossain           7.96       11            12.18
3     Mohammad Naveed           5.24       11            13.18
4         Rashid Khan           6.51       11            18.36
5           HH Pandya           7.01       11            18.81
6        PWH de Silva           7.39        9            18.88
7         Shadab Khan           6.05        8            14.12
8          Haris Rauf           7.65        8            19.12
9      Mohammad Nawaz           7.05        8            21.75
10      Mohammad Amir           5.06        7            11.57
11    KMDN Kulasekara           6.33        7            13.57
12   Mujeeb Ur Rahman           5.55        7            15.85
13        Naseem Shah           7.66        7            19.71
14      C Karunaratne           9.06        7            20.71
15      Mohammad Nabi           7.24        7            30.00
16    PM Liyanagamage           8.91        6             9.16
17          JJ Bumrah           5.22        6            15.66
18            A Nehra           7.07        6            16.50
19           R Ashwin           6.50        6            23.83
20      Rohan Mustafa           7.00        6            24.33
21   Fazalhaq Farooqi           8.36        6            25.33
22    Shakib Al Hasan           6.16        6            25.33
23       D Madushanka           7.75        6            25.83
24       M Theekshana           6.75        6            27.00
25     Mohammad Irfan           5.43        5            17.40
26       Fareed Ahmad          11.00        5            17.60
27   Mashrafe Mortaza           7.12        5            22.80
28       Taskin Ahmed           6.00        5            27.60
29     Arshdeep Singh           8.62        5            30.20
30         SL Malinga           6.50        4             6.50
31        Mahmudullah           4.66        4             7.00
32       Nadeem Ahmed           6.41        4            19.25
33       Aamir Kaleem           8.40        4            21.00
34         Bilal Khan           8.27        4            22.75
35          RA Jadeja           5.88        4            26.50
36          YS Chahal           7.93        4            31.75
37   Mohammad Hasnain           8.93        4            33.50
38  Mustafizur Rahman           7.05        4            33.50
39   Mohammad Shahzad           8.13        4            39.00
40         Aizaz Khan          10.80        4            47.25

In [50]:
player = pd.concat([batdf,balldf], ignore_index = True, sort = False)
player

,Player Name,Batting Average,Balls Faced,Fours,Sixes,Economy Rate,Wickets,Bowling Average
0,V Kohli,85.80,325.0,40.0,11.0,NaN,NaN,NaN
1,Mohammad Rizwan,56.20,239.0,21.0,6.0,NaN,NaN,NaN
2,RG Sharma,30.11,192.0,27.0,12.0,NaN,NaN,NaN
3,Babar Hayat,47.00,160.0,22.0,10.0,NaN,NaN,NaN
4,Ibrahim Zadran,65.33,188.0,14.0,4.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
85,YS Chahal,NaN,NaN,NaN,NaN,7.93,4.0,31.75
86,Mohammad Hasnain,NaN,NaN,NaN,NaN,8.93,4.0,33.50
87,Mustafizur Rahman,NaN,NaN,NaN,NaN,7.05,4.0,33.50
88,Mohammad Shahzad,NaN,NaN,NaN,NaN,8.13,4.0,39.00
89,Aizaz Khan,NaN,NaN,NaN,NaN,10.80,4.0,47.25

In [54]:
player.fillna(value='NA', inplace=True)
player

,Player Name,Batting Average,Balls Faced,Fours,Sixes,Economy Rate,Wickets,Bowling Average
0,V Kohli,85.80,325.0,40.0,11.0,NA,NA,NA
1,Mohammad Rizwan,56.20,239.0,21.0,6.0,NA,NA,NA
2,RG Sharma,30.11,192.0,27.0,12.0,NA,NA,NA
3,Babar Hayat,47.00,160.0,22.0,10.0,NA,NA,NA
4,Ibrahim Zadran,65.33,188.0,14.0,4.0,NA,NA,NA
...,...,...,...,...,...,...,...,...
85,YS Chahal,NA,NA,NA,NA,7.93,4.0,31.75
86,Mohammad Hasnain,NA,NA,NA,NA,8.93,4.0,33.5
87,Mustafizur Rahman,NA,NA,NA,NA,7.05,4.0,33.5
88,Mohammad Shahzad,NA,NA,NA,NA,8.13,4.0,39.0
89,Aizaz Khan,NA,NA,NA,NA,10.8,4.0,47.25