In [18]:
# importing necessary libraries.
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot  as plt

In [19]:
# importing dataset....
keeper_odi = pd.read_csv('wicketkeeper data odi.csv')
keeper_odi

,Player Name,Country,Time Period,Matches,Played,Dismissals,Catches,Stumpings,Maximum Dismissals
0,MS Dhoni,India,2008-2018,19,19,36,25,11,5
1,KC Sangakkara,Sri Lanka,2004-2014,24,24,36,27,9,4
2,Moin Khan,Pakistan,1995-2004,14,13,17,12,5,3
3,Mushfiqur Rahim,Bangladesh,2008-2018,21,17,17,14,3,4
4,DSBP Kuruppu,Sri Lanka,1984-1988,9,9,14,12,2,4
5,RS Kaluwitharana,Sri Lanka,1995-2000,8,8,11,9,2,5
6,Khaled Mashud,Bangladesh,1995-2004,14,14,11,8,3,3
7,Sarfaraz Ahmed,Pakistan,2008-2018,13,13,10,8,2,3
8,Zulqarnain,Pakistan,1986-1986,3,3,9,8,1,4
9,R Dravid,India,1997-2004,13,5,7,5,2,2
10,NR Mongia,India,1995-2000,5,5,7,7,0,3
11,Umar Akmal,Pakistan,2010-2014,12,6,7,5,2,2
12,Amjad Ali,UAE,2008-2008,2,2,5,4,1,3
13,Mohammad Shahzad,Afghanistan,2014-2018,9,9,5,4,1,1
14,Litton Das,Bangladesh,2018-2018,6,1,4,1,3,2
15,SS McKechnie,Hong Kong,2018-2018,2,2,4,4,0,2
16,HP Tillakaratne,Sri Lanka,1988-1995,9,3,4,3,1,2
17,Anamul Haque,Bangladesh,2014-2014,4,4,4,4,0,3
18,KD Karthik,India,2010-2018,12,4,4,3,1,2
19,Anil Dalpat,Pakistan,1984-1984,2,2,3,2,1,2
20,SC Khanna,India,1984-1984,2,2,3,1,2,2
21,Saleem Yousuf,Pakistan,1988-1988,2,2,3,3,0,2
22,SKL de Silva,Sri Lanka,1997-1997,3,3,3,1,2,2
23,Kamran Akmal,Pakistan,2010-2010,3,3,3,3,0,1
24,SS Karim,India,1997-2000,5,5,3,3,0,2
25,KS More,India,1988-1991,5,5,3,3,0,2
26,TM Dilshan,Sri Lanka,2000-2012,20,0,2,2,0,2
27,CI Dunusinghe,Sri Lanka,1995-1995,1,1,2,1,1,2
28,TT Smart,Hong Kong,2004-2004,2,1,2,2,0,2
29,JJ Atkinson,Hong Kong,2008-2008,2,2,2,1,1,2
30,Hafizur Rahman,Bangladesh,1986-1986,2,2,2,2,0,1
31,CS Pandit,India,1988-1988,2,2,2,1,1,2
32,PA Patel,India,2004-2004,2,2,2,2,0,1
33,MDKJ Perera,Sri Lanka,2014-2018,7,2,2,2,0,2
34,Nasir Ahmed,Bangladesh,1988-1990,5,5,2,1,1,1
35,Aamer Malik,Pakistan,1988-1988,2,1,1,0,1,1
36,Javed Qadeer,Pakistan,1995-1995,1,1,1,1,0,1
37,Abdul Rehman,UAE,2004-2004,1,1,0,0,0,0
38,Asghar Ali,UAE,2004-2004,2,1,0,0,0,0
39,Nasir Hameed,Hong Kong,2004-2004,1,1,0,0,0,0

In [20]:
features = ['Player Name', 'Catches','Stumpings','Maximum Dismissals']
keeper_odi = keeper_odi.dropna(subset=features) # remove rows not dont have numerical value from the features.
keeper_odi = keeper_odi[features].copy()
keeper_odi

          Player Name  Catches  Stumpings  Maximum Dismissals
0           MS Dhoni        25         11                   5
1      KC Sangakkara        27          9                   4
2          Moin Khan        12          5                   3
3    Mushfiqur Rahim        14          3                   4
4       DSBP Kuruppu        12          2                   4
5   RS Kaluwitharana         9          2                   5
6      Khaled Mashud         8          3                   3
7     Sarfaraz Ahmed         8          2                   3
8         Zulqarnain         8          1                   4
9           R Dravid         5          2                   2
10         NR Mongia         7          0                   3
11        Umar Akmal         5          2                   2
12         Amjad Ali         4          1                   3
13  Mohammad Shahzad         4          1                   1
14        Litton Das         1          3                   2
15      SS McKechnie         4          0                   2
16   HP Tillakaratne         3          1                   2
17      Anamul Haque         4          0                   3
18        KD Karthik         3          1                   2
19       Anil Dalpat         2          1                   2
20         SC Khanna         1          2                   2
21     Saleem Yousuf         3          0                   2
22      SKL de Silva         1          2                   2
23      Kamran Akmal         3          0                   1
24          SS Karim         3          0                   2
25           KS More         3          0                   2
26        TM Dilshan         2          0                   2
27     CI Dunusinghe         1          1                   2
28          TT Smart         2          0                   2
29       JJ Atkinson         1          1                   2
30    Hafizur Rahman         2          0                   1
31         CS Pandit         1          1                   2
32          PA Patel         2          0                   1
33       MDKJ Perera         2          0                   2
34       Nasir Ahmed         1          1                   1
35       Aamer Malik         0          1                   1
36      Javed Qadeer         1          0                   1
37      Abdul Rehman         0          0                   0
38        Asghar Ali         0          0                   0
39      Nasir Hameed         0          0                   0

In [21]:
# scaling the data.
scaler = StandardScaler()
features = ['Catches','Stumpings','Maximum Dismissals']
scaled_data = pd.DataFrame( scaler.fit_transform(keeper_odi[features]) , columns = features )
scaled_data

     Catches  Stumpings  Maximum Dismissals
0   3.382973   4.197471            2.350599
1   3.718752   3.316112            1.518528
2   1.200410   1.553395            0.686458
3   1.536189   0.672036            1.518528
4   1.200410   0.231357            1.518528
5   0.696741   0.231357            2.350599
6   0.528852   0.672036            0.686458
7   0.528852   0.231357            0.686458
8   0.528852  -0.209323            1.518528
9   0.025183   0.231357           -0.145612
10  0.360962  -0.650002            0.686458
11  0.025183   0.231357           -0.145612
12 -0.142706  -0.209323            0.686458
13 -0.142706  -0.209323           -0.977683
14 -0.646375   0.672036           -0.145612
15 -0.142706  -0.650002           -0.145612
16 -0.310596  -0.209323           -0.145612
17 -0.142706  -0.650002            0.686458
18 -0.310596  -0.209323           -0.145612
19 -0.478485  -0.209323           -0.145612
20 -0.646375   0.231357           -0.145612
21 -0.310596  -0.650002           -0.145612
22 -0.646375   0.231357           -0.145612
23 -0.310596  -0.650002           -0.977683
24 -0.310596  -0.650002           -0.145612
25 -0.310596  -0.650002           -0.145612
26 -0.478485  -0.650002           -0.145612
27 -0.646375  -0.209323           -0.145612
28 -0.478485  -0.650002           -0.145612
29 -0.646375  -0.209323           -0.145612
30 -0.478485  -0.650002           -0.977683
31 -0.646375  -0.209323           -0.145612
32 -0.478485  -0.650002           -0.977683
33 -0.478485  -0.650002           -0.145612
34 -0.646375  -0.209323           -0.977683
35 -0.814264  -0.209323           -0.977683
36 -0.646375  -0.650002           -0.977683
37 -0.814264  -0.650002           -1.809753
38 -0.814264  -0.650002           -1.809753
39 -0.814264  -0.650002           -1.809753

In [22]:
''' To find how many clusers are to be formed '''
def elbow_plot( min_k, max_k, k_max_iter):
    sum_squared_distances = []
    k_range = range(min_k,max_k+1)
    for k in k_range:
        km = KMeans(n_clusters=k, max_iter=k_max_iter, n_init=10)
        km.fit(scaled_data)
        sum_squared_distances.append(km.inertia_)
        
    # Plot the score for each value of k
    plt.plot(k_range, sum_squared_distances, 'bx-')
    plt.xlabel('k')
    plt.ylabel('Sum of squared distances')
    plt.title('Elbow Method For Optimal k')
    plt.show()

In [23]:
# elbow_plot(2,12,15)

In [24]:
# Clustering the players using k-means algorithm.
km = KMeans(n_clusters=3,n_init=50)
scaled_data['Cluster'] = km.fit_predict(scaled_data) # assigning the cluster number for each datapoint in the dataframe.
scaled_data

C:\Users\Home\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

     Catches  Stumpings  Maximum Dismissals  Cluster
0   3.382973   4.197471            2.350599        1
1   3.718752   3.316112            1.518528        1
2   1.200410   1.553395            0.686458        2
3   1.536189   0.672036            1.518528        2
4   1.200410   0.231357            1.518528        2
5   0.696741   0.231357            2.350599        2
6   0.528852   0.672036            0.686458        2
7   0.528852   0.231357            0.686458        2
8   0.528852  -0.209323            1.518528        2
9   0.025183   0.231357           -0.145612        0
10  0.360962  -0.650002            0.686458        2
11  0.025183   0.231357           -0.145612        0
12 -0.142706  -0.209323            0.686458        2
13 -0.142706  -0.209323           -0.977683        0
14 -0.646375   0.672036           -0.145612        0
15 -0.142706  -0.650002           -0.145612        0
16 -0.310596  -0.209323           -0.145612        0
17 -0.142706  -0.650002            0.686458        2
18 -0.310596  -0.209323           -0.145612        0
19 -0.478485  -0.209323           -0.145612        0
20 -0.646375   0.231357           -0.145612        0
21 -0.310596  -0.650002           -0.145612        0
22 -0.646375   0.231357           -0.145612        0
23 -0.310596  -0.650002           -0.977683        0
24 -0.310596  -0.650002           -0.145612        0
25 -0.310596  -0.650002           -0.145612        0
26 -0.478485  -0.650002           -0.145612        0
27 -0.646375  -0.209323           -0.145612        0
28 -0.478485  -0.650002           -0.145612        0
29 -0.646375  -0.209323           -0.145612        0
30 -0.478485  -0.650002           -0.977683        0
31 -0.646375  -0.209323           -0.145612        0
32 -0.478485  -0.650002           -0.977683        0
33 -0.478485  -0.650002           -0.145612        0
34 -0.646375  -0.209323           -0.977683        0
35 -0.814264  -0.209323           -0.977683        0
36 -0.646375  -0.650002           -0.977683        0
37 -0.814264  -0.650002           -1.809753        0
38 -0.814264  -0.650002           -1.809753        0
39 -0.814264  -0.650002           -1.809753        0

In [25]:
scaled_data.insert(0,'Player Name',keeper_odi['Player Name']) # adding player name to the cluster...
scaled_data

          Player Name   Catches  Stumpings  Maximum Dismissals  Cluster
0           MS Dhoni   3.382973   4.197471            2.350599        1
1      KC Sangakkara   3.718752   3.316112            1.518528        1
2          Moin Khan   1.200410   1.553395            0.686458        2
3    Mushfiqur Rahim   1.536189   0.672036            1.518528        2
4       DSBP Kuruppu   1.200410   0.231357            1.518528        2
5   RS Kaluwitharana   0.696741   0.231357            2.350599        2
6      Khaled Mashud   0.528852   0.672036            0.686458        2
7     Sarfaraz Ahmed   0.528852   0.231357            0.686458        2
8         Zulqarnain   0.528852  -0.209323            1.518528        2
9           R Dravid   0.025183   0.231357           -0.145612        0
10         NR Mongia   0.360962  -0.650002            0.686458        2
11        Umar Akmal   0.025183   0.231357           -0.145612        0
12         Amjad Ali  -0.142706  -0.209323            0.686458        2
13  Mohammad Shahzad  -0.142706  -0.209323           -0.977683        0
14        Litton Das  -0.646375   0.672036           -0.145612        0
15      SS McKechnie  -0.142706  -0.650002           -0.145612        0
16   HP Tillakaratne  -0.310596  -0.209323           -0.145612        0
17      Anamul Haque  -0.142706  -0.650002            0.686458        2
18        KD Karthik  -0.310596  -0.209323           -0.145612        0
19       Anil Dalpat  -0.478485  -0.209323           -0.145612        0
20         SC Khanna  -0.646375   0.231357           -0.145612        0
21     Saleem Yousuf  -0.310596  -0.650002           -0.145612        0
22      SKL de Silva  -0.646375   0.231357           -0.145612        0
23      Kamran Akmal  -0.310596  -0.650002           -0.977683        0
24          SS Karim  -0.310596  -0.650002           -0.145612        0
25           KS More  -0.310596  -0.650002           -0.145612        0
26        TM Dilshan  -0.478485  -0.650002           -0.145612        0
27     CI Dunusinghe  -0.646375  -0.209323           -0.145612        0
28          TT Smart  -0.478485  -0.650002           -0.145612        0
29       JJ Atkinson  -0.646375  -0.209323           -0.145612        0
30    Hafizur Rahman  -0.478485  -0.650002           -0.977683        0
31         CS Pandit  -0.646375  -0.209323           -0.145612        0
32          PA Patel  -0.478485  -0.650002           -0.977683        0
33       MDKJ Perera  -0.478485  -0.650002           -0.145612        0
34       Nasir Ahmed  -0.646375  -0.209323           -0.977683        0
35       Aamer Malik  -0.814264  -0.209323           -0.977683        0
36      Javed Qadeer  -0.646375  -0.650002           -0.977683        0
37      Abdul Rehman  -0.814264  -0.650002           -1.809753        0
38        Asghar Ali  -0.814264  -0.650002           -1.809753        0
39      Nasir Hameed  -0.814264  -0.650002           -1.809753        0

In [26]:
# spliting the dataframe into diffrent clusters.
b0 = scaled_data.loc[scaled_data['Cluster']==0]
b1 = scaled_data.loc[scaled_data['Cluster']==1]
b2 = scaled_data.loc[scaled_data['Cluster']==2]

In [27]:
len(b0)

28

In [28]:
len(b1)

2

In [29]:
len(b2)

10